stages:
  - test

test:
  image: 10.0.0.20/ponycool/php-deploy-8.2:latest
  before_script:
    - apt install -y make
    - composer config -g repo.packagist composer https://packagist.phpcomposer.com
    - composer install
  script:
    - make test
  cache:
    paths:
      - vendor/